language: ruby
rvm:
- 2.0

# branch whitelist
branches:
  only:
  - master
  - /dev-(.*)/
install:
- travis_retry npm install
- travis_retry bower install
- travis_retry bundle install

script: jekyll build && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
