language: ruby
rvm:
- 2.0

# branch whitelist
branches:
  only:
  - master
  - /dev-(.*)/
install:
- travis_retry npm install
- travis_retry bower install
- travis_retry bundle install

script: jekyll build && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
  irc:
  template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
  channels:
    - irc.swiftirc.net#commits
