# Site Settings
title : Amanda's Drivel
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
tagline: Sometimes I make things
url: "http://yourdomain.com"
author :
  name : Amanda Folson
  email : hahanicetry@spamme.rs
  github : afolson
  twitter : AmbassadorAwsum
  linkedin: https://www.linkedin.com/in/violins

# Site Collections
collections:
  projects:
    title: "Projects"
    output: true
    permalink: /projects/:path/
  writing:
    title: "Writing"
    output: true
    permalink: /writing/:path/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
